---

- name: restart {{ celery_application_name }}
  supervisorctl: name={{ celery_application_name }} state=restarted

- name: restart {{ celerybeat_application_name }}
  supervisorctl: name={{ celerybeat_application_name }} state=restarted