---

- name: restart celery workers
  supervisorctl:
    name: "celery_{{ item.name }}"
    state: restarted
  with_items: "{{ celery_worker }}"

- name: restart celery beat
  supervisorctl: name={{ celerybeat_application_name }} state=restarted