---

- name: Create a {{ application_name }}
  hosts: all
  become: yes
  become_user: root
  remote_user: sw
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/production.yml

  roles:
    - base
    - db
    - memcached
    - rabbitmq
    - elasticsearch
    - web
    - celery
    - certbot
    - nginx
    - postfix
    - dovecot
    - backup
