---

- name: Create the Supervisor config file for {{ item }}
  template: src=supervisor_{{ item }}.conf.j2
            dest=/etc/supervisor/conf.d/{{ item }}.conf
  with_items:
    - "{{ celery_application_name }}"
    - "{{ celerymail_application_name }}"
    - "{{ celerybeat_application_name }}"
  tags:
    - celery

- name: Create the {{ celery_application_name }} log directory
  file: path={{ celery_log_dir }}
        owner={{ celery_user }}
        group={{ celery_group }}
        state=directory
  tags:
    - celery

- name: Create the {{ celery_application_name }} log file
  file: path={{ celery_log_file }}
        owner={{ celery_user }}
        group={{ celery_group }}
        state=touch
  tags:
    - celery

- name: Create the {{ celerymail_application_name }} log file
  file: path={{ celerymail_log_file }}
        owner={{ celery_user }}
        group={{ celery_group }}
        state=touch
  tags:
    - celery

- name: Create the {{ celerybeat_application_name }} log file
  file: path={{ celerybeat_log_file }}
        owner={{ celery_user }}
        group={{ celery_group }}
        state=touch
  tags:
    - celery

- name: Re-read the Supervisor config files
  command: supervisorctl reread
  tags:
    - celery

- name: Update Supervisor to add the app in the process group
  command: supervisorctl update
  tags:
    - celery