---

- name: Add certboot apt repo
  apt_repository: repo="ppa:certbot/certbot" update_cache=false

- name: Ensure software-properties-common installed
  apt: name=software-properties-common state=latest
  register: certbot_repo_added

- apt: update_cache=true
  when: certbot_repo_added | changed

- name: Install Certbot.
  apt: name=certbot state=latest

- name: Check if Nginx exists
  stat: path=/etc/init.d/nginx
  register: nginx_status

- name: Ensure Nginx is stopped
  service: name=nginx state=stopped
  when: nginx_status.stat.exists

- name: Install certbot and generate cert
  command: "{{ certbot_script }} certonly --noninteractive --agree-tos --standalone --email {{ certbot_admin_email }} -d {{ hostname }} -d www.{{ hostname }}"
  args:
    creates: "{{ certbot_output_dir }}"

- name: Ensure Nginx is started
  service: name=nginx state=started
  when: nginx_status.stat.exists

- name: Ensure a cron job to auto-renew the cert exists
  cron: name="daily auto renew cert"
        special_time=daily
        job="{{ certbot_script }} renew --standalone --no-self-upgrade --pre-hook \"service nginx stop\" --post-hook \"service nginx start\" --quiet"
        state=present
  when: certbot_auto_renew
