---

- name: Install additional packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - gettext
    - imagemagick

- name: Add LibreOffice repository
  apt_repository: repo="ppa:libreoffice/libreoffice-5-3" state=present

- name: Install LibreOffice
  apt: name=libreoffice state=latest update_cache=yes
