---

- name: Install additional packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=present
  with_items:
    - gettext
    - imagemagick
    - tesseract-ocr
    - libtesseract-dev
    - libleptonica-dev
    - poppler-utils
    - qpdf

- name: Install tesseract data
  get_url:
    url: "{{ item }}"
    # Remove tessdata here for tesseract > 4 in Ubuntu 18.04
    dest: "{{ tesseract_data_path }}tessdata/{{ item | basename }}"
    mode: '0444'
  with_items:
    - https://raw.githubusercontent.com/tesseract-ocr/tessdata/3.04.00/deu.traineddata
  when: ansible_distribution_version == "16.04"

- name: Install tesseract 4 data
  get_url:
    url: "{{ item }}"
    dest: "{{ tesseract_data_path }}{{ item | basename }}"
    mode: '0444'
  with_items:
    - https://raw.githubusercontent.com/tesseract-ocr/tessdata/4.00/deu.traineddata
  when: ansible_distribution_version == "18.04"

- name: Add LibreOffice repository
  apt_repository: repo="ppa:libreoffice/libreoffice-5-3" state=present
  when: ansible_distribution_version == "16.04"

- name: Add LibreOffice repository
  apt_repository: repo="ppa:libreoffice/libreoffice-6-0" state=present
  when: ansible_distribution_version == "18.04"

- name: Install LibreOffice
  apt: name=libreoffice state=latest update_cache=yes

- name: Install Latex for PDF generation
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=present
  with_items:
    - texlive
    - latexmk
