---

- import_tasks: install_additional_packages.yml
  tags: packages

- import_tasks: create_users_and_groups.yml

- import_tasks: set_file_permissions.yml
  tags: deploy

- import_tasks: setup_virtualenv.yml
  tags: virtualenv

- import_tasks: setup_git_repo.yml
  tags: deploy

- import_tasks: set_file_permissions.yml
  tags: deploy

- import_tasks: setup_django_app.yml
  tags: deploy

- import_tasks: setup_geoip.yml
  tags: deploy

- import_tasks: setup_supervisor.yml
  tags: supervisor

- import_tasks: run_django_tasks.yml
  tags: deploy

- name: restart application
  supervisorctl: name={{ application_name }} state=restarted

- import_tasks: setup_cron_tasks.yml
  tags: maintenance
