---

- name: Run Django database migrations
  django_manage:
    command: "migrate --noinput"
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  tags: django.migrate
  become: true
  become_user: "{{ gunicorn_user }}"

- name: Run Django collectstatic
  django_manage:
    command: "collectstatic --noinput --clear -v 0"
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  tags: django.collectstatic
  become: true
  become_user: "{{ gunicorn_user }}"

- name: Run Django compress
  django_manage:
    command: compress
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  tags: django.compress
  become: true
  become_user: "{{ gunicorn_user }}"
  when: django_configuration != "Dev"

- name: Run Django compilemessages
  django_manage:
    command: "compilemessages -l de"
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  tags: django.compress
  become: true
  become_user: "{{ gunicorn_user }}"
