---

- name: Install JRE
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=present
  with_items:
    - default-jre
  tags: packages

- name: Check if elasticsearch present
  stat: path=/usr/share/elasticsearch/bin/elasticsearch
  register: elasticsearch_config

- name: Get elasticsearch release
  get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.3.2.deb"
    dest: "/tmp/elasticsearch-6.3.2.deb"
  when: not elasticsearch_config.stat.exists

- name: Install elasticsearch
  command: dpkg -i /tmp/elasticsearch-6.3.2.deb
  when: not elasticsearch_config.stat.exists

- name: Install elasticsearch extensions
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin install -b http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-plugin-bundle/6.3.2.1/elasticsearch-plugin-bundle-6.3.2.1.zip
  when: not elasticsearch_config.stat.exists

- name: Ensure elasticsearch service is running
  service: name=elasticsearch state=started enabled=yes
