---

celery_user: "{{ application_name }}"
celery_group: webapps

celery_scripts_dir: "{{ virtualenv_path }}/scripts/celery"

celerybeat_application_name: celerybeat
celerybeat_template_file: "{{ celerybeat_application_name }}_start.j2"

celery_log_dir: "{{ virtualenv_path }}/logs"

celerybeat_log_file: "{{ celery_log_dir }}/{{ celerybeat_application_name }}.log"
